Pr branch
StudioShader/ScalaBoyz pull request #6
Opened 2021-04-16 18:37 UTC by StudioShader

2021-04-19 05:45 UTC, fuCtor requested changes

2021-04-19 05:45 UTC, fuCtor commented on src/main/scala/org/myapp/DateTime.scala
> +case class DateTime(var date: LocalDate){
Не имеет смысла,  либо заводить тип для начала и тип для конца события, но в таком виде нет какой-то особой смысловой нагрузки в этом типе.

2021-04-19 05:45 UTC, fuCtor commented on src/main/scala/org/myapp/Calendar.scala
> +object Calendar {
Мутабельный коллекции не хорошо использовать в таком виде, какую задачу выполняет этот объект? Вроде и отдельно хранилище событий есть, не понятен смысл.

2021-04-19 05:45 UTC, fuCtor commented on src/main/scala/org/myapp/Event.scala
> +    var notificationTime: DateTime = DateTime.now()
Лучше вынести в параметр события, иначе получается не чистый объект и если нужно будет изменить  name через метод copy, то и notificationTime тоже изменится.

2021-04-19 05:45 UTC, fuCtor commented on src/main/scala/org/myapp/EventStorage.scala
> +  val heap: F[Event]
Для чего это значение?

2021-04-19 05:45 UTC, fuCtor commented on src/main/scala/org/myapp/EventStorage.scala
> +  def getEventsByDate(date: DateTime): Vector[Event] = ???
Если мы объявляем trait как некоторый интерфейс, то реализации метод не обязательны, тем более в таком виде.

2021-04-19 05:45 UTC, fuCtor commented on src/main/scala/org/myapp/EventStorage.scala
> +  def redactEvent(event: Event, event2: Event): Unit = ???
Может лучше назвать updateEvent? и не обязательно передавать два события, можно передать измененное только, так как оно должно в любом случае содержать идентификатор изначального события.

2021-04-19 05:45 UTC, fuCtor commented on src/main/scala/org/myapp/Event.scala
> +case class Event(var date: DateTime,
Необходимо добавить поле с идентификатором события.

2021-04-19 05:45 UTC, fuCtor commented on src/main/scala/org/myapp/UserStorage.scala
> +  val heap: F[User]
Аналогично, для чего это?

2021-05-01 17:46 UTC, StudioShader commented on src/main/scala/org/myapp/DateTime.scala
> +case class DateTime(var date: LocalDate){
В ней есть смысл. Потому что возможно в будущем я захочу использовать не LocalDate а другой встроенный класс для времени. И тогда мне надо будет только поменять методы в DateTime а не везде в коде, так как это будет много где использоваться.

2021-05-01 17:55 UTC, StudioShader commented on src/main/scala/org/myapp/Calendar.scala
> +object Calendar {
mutable я использую для того, что бы мочь изменять list эвентов как угодно. Как в с++. А сам календарь выполняет функцию обёртки над этим хранилищем. Возможно он пока действительно не нужен но в задании было написанно "компонент для хранения событий;" вот я его и сделал.

2021-05-01 17:56 UTC, StudioShader commented on src/main/scala/org/myapp/Event.scala
> +    var notificationTime: DateTime = DateTime.now()
понял. Логично, вынесу в следующем задании.

2021-05-01 17:57 UTC, StudioShader commented on src/main/scala/org/myapp/EventStorage.scala
> +  val heap: F[Event]
место где непосредственно будут храниться все события

2021-05-01 17:58 UTC, StudioShader commented on src/main/scala/org/myapp/EventStorage.scala
> +  def getEventsByDate(date: DateTime): Vector[Event] = ???
понял. Логично. Исправим

2021-05-01 17:59 UTC, StudioShader commented on src/main/scala/org/myapp/EventStorage.scala
> +  def redactEvent(event: Event, event2: Event): Unit = ???
Вот не особо понятно, как и почему оно должно содержать этот идентификатор. Может быть событие перенесли и от прежнего события не осталось ни даты ни названия

2021-05-01 17:59 UTC, StudioShader commented on src/main/scala/org/myapp/Event.scala
> +case class Event(var date: DateTime,
Вот теперь понял. Да

2021-05-01 18:00 UTC, StudioShader commented on src/main/scala/org/myapp/UserStorage.scala
> +  val heap: F[User]
место где непосредственно будут находиться юзеры

2021-05-04 06:09 UTC, fuCtor commented on src/main/scala/org/myapp/DateTime.scala
> +case class DateTime(var date: LocalDate){
Типы данных лучше не прятать, так как они сами по себе несут разный смысл и лучше видеть его.
Например если спрятать тип, то не понятно, есть ли у него часовой пояс или нет, если нет, то в каком часовом поясе это значения хранится и тд.

2021-05-04 06:11 UTC, fuCtor commented on src/main/scala/org/myapp/Calendar.scala
> +object Calendar {
Компонент для хранения событий это реализация некоторого trait, который прячет доступ к данным и возможны различные реализации, в частности InMemory вариант используется для хранения ConcurrentHashMap.
Для чего это объяснялось на последних нескольки лекциях/практиках.

2021-05-04 06:13 UTC, fuCtor commented on src/main/scala/org/myapp/EventStorage.scala
> +  val heap: F[Event]
Все события, а тип Event, как то не вяжется + в trait не нужно это прописывать, так как хранится это может в файле, БД, другом внешнем сервисе, поэтому это нельзя никак описать единообразно.

2021-05-04 06:14 UTC, fuCtor commented on src/main/scala/org/myapp/EventStorage.scala
> +  def redactEvent(event: Event, event2: Event): Unit = ???
Но от прежнего в любом случае должен быть его идентификатор, мы же обновляем событие Х, то оба параметра должны быть событиями Х.

2021-05-04 06:15 UTC, fuCtor commented on src/main/scala/org/myapp/UserStorage.scala
> +  val heap: F[User]
Ответил выше по аналогичному пункту.

2021-05-05 13:45 UTC, closed without merging